### ISSUE TITLE
German Umlaut in Einstein Reference

### ISSUE THREAD

**Issue by ermeel86** [bob-carpenter/prob-stats#3]
Hi,

this is really a minor cosmetic aspect but since I am German speaker I thought I let you know, before I forget it:

The RMarkdown for the section "7 Statistical Inference and Inverse Problems" contains the following reference:

>116 Einstein, Albert. 1907. On the relativity principle and the conclusions drawn from it. Jahrbuch der Radioaktivitﬁt and Elektronik 4:411–462.

The journal ist actually called

>Jahrbuch der Radioaktivität und Elektronik

and the original title of his work was

> Über das Relativitätsprinzip und die aus demselben gezogenen Folgerungen

**Comment by bob-carpenter** [comment]
Thanks.  I fixed it.
