### ISSUE TITLE
PDFs do not build 

### ISSUE THREAD

**Issue by dr-manhattan** [bob-carpenter/prob-stats#4]
Tried on both Ubuntu and Mac. Same (unclear) error in _main.log

! Extra alignment tab has been changed to \cr.
<recently read> \endtemplate

l.1800 &
         = &
Here is how much of TeX's memory you used:
 13684 strings out of 492649
 194607 string characters out of 6129622
 303592 words of memory out of 5000000
 17170 multiletter control sequences out of 15000+600000
 87392 words of font info for 153 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 45i,13n,45p,601b,461s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!

**Comment by ermeel86** [comment]
Same here (except for the numbers).

**Comment by bob-carpenter** [comment]
Thanks.  That was just the tip of the iceberg.  bookdown is happy formatting html with all kinds of errors in it, but LaTeX is pickier.  I'm fixing all this so it'll compile.
